// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btytqmuouzgsofdanqew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0eXRxbXVvdXpnc29mZGFucWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjQ0MjIsImV4cCI6MjA2MzYwMDQyMn0.pWRPHW8DyIeSs1t2Gyh3_yRdKnLSduRAZkfcAJU9Hvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);